### ISSUE TITLE
Add projectRoot option.

### ISSUE THREAD

**Issue by SoonDead** [gandm/language-babel#107] opened 2015-11-10 14:24 UTC
This is my `.babelrc` one folder above the jsx file I'm editing:

    {
        presets: [ "react", "es2015", "stage-2"]
    }

Transpile on save shows the following error:

    Couldn't find preset "react"
 
    Using babel-core at
    C:\[omitted]\.atom\packages\language-babel\node_modules\babel-core\index.js

Issuing `npm install babel-preset-react` in `C:\[omitted]\.atom\packages\language-babel\` does not help.

**Comment by gandm** [comment] 2015-11-10 15:15
If you are using > V2.0.0 of language-babel then you must install `babel-core` and all presets\plugins into the projects root node_modules folder. See https://github.com/gandm/example-language-babel for an example. Also, read the [readme](https://github.com/gandm/language-babel/blob/master/README.md) section **Interface to Babel V6 & V5**

**Comment by SoonDead** [comment] 2015-11-10 17:35
the node_modules folder was in a subfolder of the project folder.

closing the project folder and selecting the subfolder as the project folder helped, although I want the whole project to be available on the left tree not just the subfolder.

**Comment by gandm** [comment] 2015-11-10 18:36
The problem I have is that I have to make assumptions on where the presets and plugins are located. In your case I would have to explore all sub folders looking for a node modules holding babel-core and in some cases may find more than one, and then which one should I pick and is it actually part of this project? The alternative is to have an additional .languagebabel property to determine where babel-core and the plugins are located. I think the second option is preferable.


The problem is that I don't want to reload Babel and it's plugins on each save as it’s very costly. So I run them in a task assuming that a project is using the same core and plugins as only the first save in a project loads Babel.


If I provided an additional property, such as 


{‘babelCoreDir': 'project directory holding Babel core’}


 that may get round this issue. What do you think?









From: Márton Vincze
Sent: ‎Tuesday‎, ‎10‎ ‎November‎ ‎2015 ‎17‎:‎35
To: gandm/language-babel
Cc: Graham





the node_modules folder was in a subfolder of the project folder.

closing the project folder and selecting the subfolder as the project folder helped, although I want the whole project to be available on the left tree not just the subfolder.

**Comment by SoonDead** [comment] 2015-11-11 06:15
I'm just throwing random ideas in:

How about language-babel installing presets for it's own use (inside `.atom/packages/language-babel/node_modules`)? Most of the time people will only use presets as babel plugins. Is it possible to only install them if they are required first? Or when someone checks use presets/use preset-react/use preset-stage-2 or similar in the settings. I have no idea about the technical limitations on this, but seems easy for the general user. 

Or try to find the node_modules directory where .babelrc is located.

> If I provided an additional property, such as `{‘babelCoreDir': 'project directory holding Babel core’}`
A property on what? Would it be different for each project?

**Comment by gandm** [comment] 2015-11-11 06:49
@SoonDead Thanks for your thoughts they are appreciated.

That's more or less how it used to work in versions earlier than V2. It has some real problems now as Babel V6 has far too many presets for me to keep track of and it's not really how Babel was intended to be used. There will also be many more third party plugins/presets available. Also, babel has always merged any `.babelrc` files found back to the root directory of the file system so the position of a `.babelrc` file has no relevance as many projects use this feature.

I'm pretty much decided to add two new fields to .`languagebabel `
```json
{
   "projectRoot": true,
   "nodeModulesDIr": ""
}
```
Both will be optional. Normally the projectRoot will be implied from the folder loaded in Atom but for projects that have nested babel projects one could use one or more `ProjectRoot` directives. By default node_modules will be found there but the `nodeModulesDir` can be used to point to an alternative. In your case you could just put a projectRoot directive in the folder above your jsx files and it would work.

**Comment by SoonDead** [comment] 2015-11-11 07:05
That sounds fine.

**Comment by gandm** [comment] 2015-11-12 13:14
@SoonDead You may want to try 2.4.1 as it now has an additional `.languagebabel` property `{ "projectRoot": true }` that should be positioned where the node_modules ( plugins/presets) exist for a project. See the readme for more info.

**Closed** 2015-11-12 14:02 UTC
Labels: enhancement

**Comment by SoonDead** [comment] 2015-11-13 09:53
Works as intended, thank you.
