### ISSUE TITLE
Tab not working after activating this package

### ISSUE THREAD

**Issue by kevinsimper** [gandm/language-babel#325] opened 2017-02-08 14:03 UTC
![2017-02-08 15 00 02](https://cloud.githubusercontent.com/assets/1126497/22740305/8389469e-ee0f-11e6-87d4-e9dc9df683b8.gif)

It is a pretty fresh install and it does not work suddenly when I activate this package.

```
$ atom --version
Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
$ apm list
Built-in Atom Packages (89)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.4.0
├── base16-tomorrow-light-theme@1.4.0
├── one-dark-ui@1.8.2
├── one-light-ui@1.8.2
├── one-dark-syntax@1.6.0
├── one-light-syntax@1.6.0
├── solarized-dark-syntax@1.1.1
├── solarized-light-syntax@1.1.1
├── about@1.7.2
├── archive-view@0.62.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.14.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.33.1
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.23.2
├── background-tips@0.26.1
├── bookmarks@0.43.2
├── bracket-matcher@0.85.1
├── command-palette@0.39.1
├── deprecation-cop@0.55.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.40.0
├── find-and-replace@0.204.5
├── fuzzy-finder@1.4.0
├── git-diff@1.2.0
├── go-to-line@0.31.2
├── grammar-selector@0.48.2
├── image-view@0.60.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── line-ending-selector@0.5.1
├── link@0.31.2
├── markdown-preview@0.159.3
├── metrics@1.1.3
├── notifications@0.65.1
├── open-on-github@1.2.1
├── package-generator@1.0.2
├── settings-view@0.244.0
├── snippets@1.0.4
├── spell-check@0.68.5
├── status-bar@1.6.0
├── styleguide@0.48.0
├── symbols-view@0.113.1
├── tabs@0.103.1
├── timecop@0.33.2
├── tree-view@0.211.1
├── update-package-dependencies@0.10.0
├── welcome@0.35.1
├── whitespace@0.35.0
├── wrap-guide@0.39.0
├── language-c@0.54.0
├── language-clojure@0.22.1
├── language-coffee-script@0.48.1
├── language-csharp@0.13.0
├── language-css@0.40.1
├── language-gfm@0.88.0
├── language-git@0.15.0
├── language-go@0.43.0
├── language-html@0.47.1
├── language-hyperlink@0.16.1
├── language-java@0.24.0
├── language-javascript@0.122.0
├── language-json@0.18.3
├── language-less@0.29.6
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.37.3
├── language-property-list@0.8.0
├── language-python@0.45.1
├── language-ruby@0.70.2
├── language-ruby-on-rails@0.25.1
├── language-sass@0.57.0
├── language-shellscript@0.23.0
├── language-source@0.9.0
├── language-sql@0.25.0
├── language-text@0.7.1
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.34.12
└── language-yaml@0.27.1

Community Packages (4) /Users/kevinsimper/.atom/packages
├── auto-update-packages@1.0.1
├── language-babel@2.54.1
├── monokai@0.20.0
└── zentabs@0.8.8
```

**Comment by gandm** [comment] 2017-02-08 14:14
I don't do anything with tabs outside of JSX and then only if autoIndentJSX is on. Can you try uninstalling, re-installing and restarting? I've seen issues like this when atom/packages update and atom goes into strange state.

**Comment by gandm** [comment] 2017-02-08 14:26
If that doesn't do the trick can you let me have your config.cson.

**Comment by gandm** [comment] 2017-02-08 14:34
Looking at the colour scheme is use when you enable Babel it doesn't look correct, variables don't seem to have a colour!. Can you press the grammar button at the bottom status bar and ensure that Babel is actually the grammar used?

**Comment by gandm** [comment] 2017-02-11 09:51
This appears to be an issue with Atom itself. If you have any other info that may help determination of the cause please post it here. Closing until then.

**Closed by gandm** 2017-02-11 09:51 UTC

**Comment by kevinsimper** [comment] 2017-02-11 21:18
Thank you @gandm, removed my ~/.atom and installed everything again, so it was a problem with atom.
