### ISSUE TITLE
Latest update breaks: Cannot find module 'fuzzaldrin'

### ISSUE THREAD

**Issue by nmn** [gandm/language-babel#143] opened 2016-02-09 23:26 UTC
**Atom Version**: 1.5.0
**System**: Mac OS X 10.11.2
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package, v2.15.3

### Stack Trace

Failed to activate the language-babel package

```
At Cannot find module 'fuzzaldrin'

Error: Cannot find module 'fuzzaldrin'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/ngoel/.atom/packages/language-babel/lib/auto-complete-jsx.coffee:2:19)
    at Object.<anonymous> (/Users/ngoel/.atom/packages/language-babel/lib/auto-complete-jsx.coffee:1:1)
    at Module._compile (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/ngoel/.atom/packages/language-babel/lib/main.coffee:2:19)
    at Object.<anonymous> (/Users/ngoel/.atom/packages/language-babel/lib/main.coffee:1:1)
    at Module._compile (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:722:27)
    at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package-manager.js:502:19)
    at PackageManager.module.exports.PackageManager.activate (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package-manager.js:485:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "nuclide-objc",
      "nuclide-flow",
      "nuclide-hack",
      "nuclide-ocaml",
      "nuclide-file-tree",
      "nuclide-toolbar",
      "nuclide-arcanist",
      "nuclide-clang-atom",
      "nuclide-file-tree-deux",
      "nuclide-quick-open",
      "nuclide-installer",
      "nuclide-debugger-lldb",
      "nuclide-blame-provider-hg",
      "nuclide-debugger-atom",
      "nuclide-debugger-hhvm",
      "nuclide-open-filenames-provider",
      "nuclide-blame",
      "nuclide-diff-view",
      "nuclide-blame-ui",
      "nuclide-type-hint",
      "nuclide-move-pane",
      "nuclide-code-format"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "language-babel": {}
}
```

### Installed Packages

```coffee
# User
Stylus, v2.1.2
atom-material-syntax, v0.3.2
atom-material-ui, v0.8.1
autocomplete-flow, v1.3.0
autocomplete-modules, v1.3.1
emmet, v2.4.1
java-importer, v1.4.1
language-babel, v2.15.3
language-gherkin, v1.0.3
linter, v1.11.3
linter-eslint, v6.0.0
linter-flow, v4.1.0
linter-javac, v1.5.0
linter-tslint, v0.6.0
minimap, v4.19.0
minimap-git-diff, v4.1.8
node-debugger, v1.3.2
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by gandm** [comment] 2016-02-09 23:31
Duplicate of https://github.com/gandm/language-babel/issues/142 

Atom seems at issue?

**Comment by nmn** [comment] 2016-02-09 23:44
@gandm I don't think it's Atom. I went through three version updates for atom after updating language-babel, and things didn't change.

Also, I'm using `autocomplete-flow` that also uses `fuzzaldrin` without issues.

**Comment by gandm** [comment] 2016-02-10 01:45
Did you apm install language-babel? All I do is require fuzzaldrin https://github.com/gandm/language-babel/blob/master/lib/auto-complete-jsx.coffee#L2 not much I can do if it's not found in the cache

**Comment by gandm** [comment] 2016-02-11 08:44
I'm closing as I'm pretty sure it is something wrong with the Atom package installer. I can recreate this if I remove `fuzzaldrin.js` from the `language-babel` node-modules folder and restart Atom, even though Atom has a perfectly good copy!!!

**Closed by gandm** 2016-02-11 08:44 UTC

**Comment by nmn** [comment] 2016-02-11 10:00
re-installing fixed it. Thanks.
