### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by vshen94** [gandm/language-babel#158] opened 2016-03-21 04:54 UTC
[Enter steps to reproduce below:]

1. Usually happens after closing a tab.

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [language-babel](https://github.com/gandm/language-babel) package, v2.16.0

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /Users/vshen/.atom/packages/language-babel/lib/main.coffee:46

TypeError: Cannot read property 'dispose' of undefined
    at /Users/vshen/.atom/packages/language-babel/lib/main.coffee:46:36
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:264:27)
    at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:534:18)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:512:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:681:35)
    at Workspace.module.exports.Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:720:21)
    at atom-workspace.commandRegistry.add.core:close (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:202:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:43.4.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:41.6.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  6x -0:41 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:39.2.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -0:38.8.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:36.8.0 move-panes:move-right (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:34.9.0 window:focus-pane-on-left (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:30 core:close (atom-text-editor.editor.mini.is-focused)
  2x -0:29.5.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:29.1.0 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:28.7.0 window:focus-pane-on-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:27.4.0 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:26 move-panes:move-left (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:25.2.0 move-panes:move-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:23 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:22.6.0 core:close (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "metrics",
      "symbols-view",
      "exception-reporting"
    ],
    "ignoredNames": [
      ".git",
      "*.min*",
      "*node_modules/*",
      "*img/*",
      "*generated/models/*",
      "*generated-resources/*",
      "*.png",
      "*.gif",
      "*.jpg",
      "*.jpeg",
      "devtools_readonly/*"
    ],
    "packagesWithKeymapsDisabled": [
      "autocomplete-ctags",
      "editorconfig",
      "terminal-plus",
      "git-grep-provider"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "language-babel": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
atom-ctags, v4.5.0
atom-material-ui, v1.2.9
atom-sync, v0.6.0
atom-ternjs, v0.13.2
caniuse, v0.9.0
docblockr, v0.7.3
editorconfig, v1.2.4
emmet, v2.4.2
file-icons, v1.6.18
file-types, v0.5.1
language-apache, v1.4.0
language-babel, v2.16.0
language-smarty-php, v0.5.0
language-swift, v0.4.0
linter, v1.11.3
linter-eslint, v7.1.1
mocha-test-runner, v0.4.7
move-panes, v0.2.0
pain-split, v1.4.0
php-debug, v0.2.2
phpunit, v1.2.0
pigments, v0.24.5
pretty-json, v0.4.1
project-plus, v0.7.4
react, v0.14.1
smart-tags, v0.1.0
tabs-to-spaces, v1.0.2
terminal-plus, v0.14.5
time-status, v1.1.2
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by gandm** [comment] 2016-03-21 05:32
I can only recreate when I install and use the `move-panes` package.

**Comment by gandm** [comment] 2016-03-21 05:43
In Atom 1.6. `move-pain` and  `pain-split` functionality are implemented as native features. These seem to work correctly in Atom without generating a stack trace. See blog entry http://blog.atom.io/ `Multi-pane Usage Improvements`

**Comment by gandm** [comment] 2016-03-21 14:54
As the package move-panes seems to be the root cause of this problem I'm closing this issue.

**Closed by gandm** 2016-03-21 14:54 UTC

**Comment by vshen94** [comment] 2016-03-21 23:38
Awesome, thanks!
