### ISSUE TITLE
Atom freeze everytime i try to enter character to another line

### ISSUE THREAD

**Issue by 1aGh** [gandm/language-babel#334] opened 2017-03-02 10:35 UTC
Hi,

i have thi piece of code:

{this.state.saveAs && <SaveAsDialog active={this.state.saveAs}
				handleClose={this.handleSaveAsToggle}
				obj={this.props.actualTab.md}
				saveAsObj={this.props.saveAsObj}/>}

I just want enter close tabs to another line, but everytime i try this, Atom freeze. I want to look like this:

{this.state.saveAs && <SaveAsDialog active={this.state.saveAs}
				handleClose={this.handleSaveAsToggle}
				obj={this.props.actualTab.md}
				saveAsObj={this.props.saveAsObj}
                                  />
                               }

I try this only with javascript syntax and everythink was ok.

**Comment by dodekeract** [comment] 2017-03-02 10:48
Can't reproduce.

**Comment by gandm** [comment] 2017-03-02 10:58
I can't reproduce either. When I've had reports similar to this it's generally Atom at fault when updating my package.  I would suggest uninstalling language-babel, closing atom, removing the ~/.atom/compile-cache, restart and re-install language-babel.

**Comment by gandm** [comment] 2017-03-06 09:09
Pretty sure this has nothing to do with this package, but more likely a package update issue. I'll close but if you feel this to be a package issue post some more info back here.

**Comment by 1aGh** [comment] 2017-03-10 14:33
Hi, i try to reinstall, how you suggested. And everythink was alright untill i try to change code in .js file where i used render my view. I try to modify html elemnt and Atom freeze again. Is there a way how to send you a report bug or something?

**Comment by gandm** [comment] 2017-03-10 16:02
I need

- the atom `config.cson` file contents. 
- the atom package list from `apm list`
- the atom version from `atom -v`
- the minimum file contents that exhibit the behaviour. paste here or provide a gist.
- anything that the atom developer console is displaying. launch it before editing a file that causes the problem.

**Closed** 2017-03-23 12:45 UTC
